### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by KurtDeGreeff** [Gordon-Beeming/Admin#3]
When I put admin.exe in c:\windows and launch  admin cmd from explorer bar..I get UAC prompt, click yes and then everything flashes away..no cmd prompt whatsoever.. Any ideas? Thx

**Comment by GordonBeeming** [comment]
Hi, sorry for the late reply. 

Are you just typing admin or admin cmd?

The app runs any command you type after the admin part as admin so you can do admin powershell or admin notepad if you wanted as well

**Comment by KurtDeGreeff** [comment]
I typed 'admin cmd' but just retried and now it works fine, perhaps a reboot solved the issue...
'Admin powershell' also works fine, however 'admin ise' does crash admin eg 'admin stopped working..' But this is maybe 'normal behavior' as ise only works when started from powershell. 'admin PowerShell_ISE.exe' does work fine. ;-) Is it possible to chain commands or supply arguments too? Many thanks

**Comment by GordonBeeming** [comment]
I don't think the is a way to check for a command existing. Suppose some error handling and then I could pop up the same message as the run dialog does. 

Passing arguments should work fine, I use the first arg to admin as the command and then rest as args for the command being run

**Comment by GordonBeeming** [comment]
Im going to close this issue because it seems to be working for you now. If it happens again where it just shows up and closes doing nothing I'll investigate more.
